/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_marcojonkers_mcraytracer_Raytracer */

#ifndef _Included_com_marcojonkers_mcraytracer_Raytracer
#define _Included_com_marcojonkers_mcraytracer_Raytracer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_marcojonkers_mcraytracer_Raytracer
 * Method:    renderJNI
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_marcojonkers_mcraytracer_Raytracer_renderJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
